In [1]:
import os
import time

import thetadata
from thetadata import ThetaClient
from dotenv import load_dotenv

In [2]:
# Get environment variables in .env in project root
load_dotenv()

USERNAME=os.getenv('THETAUSER')
PASSWORD=os.getenv('THETAPASS')

In [3]:
client = ThetaClient(username=USERNAME, passwd=PASSWORD)
time.sleep(8) # TODO because it isn't started yet. Need to fix

If you require API support, feel free to join our discord server! http://discord.thetadata.us
[10-27-2024 09:41:49] INFO: Starting Theta Terminal v1.6.7 Revision A...
[10-27-2024 09:41:49] INFO: Config dir: C:\Users\david\ThetaData\ThetaTerminal
[10-27-2024 09:41:50] INFO: [MDDS] Attempting login as davidmckim@gmail.com
[10-27-2024 09:41:50] INFO: [FPSS] Attempting login as davidmckim@gmail.com
[10-27-2024 09:41:51] INFO: [FPSS] CONNECTED: [nj-a.thetadata.us:20000], Bundle: STOCK.FREE, OPTION.PRO, INDEX.FREE
[10-27-2024 09:41:51] INFO: [MDDS] CONNECTED: [nj-a.thetadata.us:12000], Bundle: STOCK.FREE, OPTION.PRO, INDEX.FREE

In [4]:
client.status()

In [7]:
aapl = client.stocks_historical_eod_report(20241001, 20241030, 'aapl')
aapl

,ms_of_day,ms_of_day2,open,high,low,close,volume,count,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,,,,,
2024-10-01 17:15:31.446000-04:00,17:15:31.446000,62127504,229.50,229.650,223.74,226.21,62896292,828899,1,73,225.570,0,3,1,225.600,0,2024-10-01
2024-10-02 17:15:59.927000-04:00,17:15:59.927000,62137903,225.95,227.370,223.02,226.78,32712880,502771,1,65,227.150,0,1,65,227.270,0,2024-10-02
2024-10-03 17:16:09.545000-04:00,17:16:09.545000,62156255,225.09,226.805,223.32,225.67,33895208,513857,4,1,225.610,0,3,65,225.750,0,2024-10-03
2024-10-04 17:17:19.925000-04:00,17:17:19.925000,62239692,227.89,228.000,224.13,226.80,37225427,556324,2,7,226.630,0,2,73,226.650,0,2024-10-04
2024-10-07 17:15:01.254000-04:00,17:15:01.254000,62101024,224.50,225.690,221.33,221.69,39146432,602939,2,1,221.880,0,3,7,221.900,0,2024-10-07
2024-10-08 17:17:18.325000-04:00,17:17:18.325000,62229409,224.29,225.980,223.25,225.77,31425054,493692,2,1,225.440,0,3,1,225.470,0,2024-10-08
2024-10-09 17:15:28.489000-04:00,17:15:28.489000,62128167,225.14,229.750,224.83,229.54,32237264,517024,5,7,229.180,0,1,65,229.220,0,2024-10-09
2024-10-10 17:15:33.941000-04:00,17:15:33.941000,62131372,227.79,229.500,227.17,229.04,28032274,445342,1,1,229.110,0,1,7,229.150,0,2024-10-10
2024-10-11 17:16:25.092000-04:00,17:16:25.092000,62172119,229.32,229.410,227.34,227.55,31330380,483675,1,1,227.480,0,3,1,227.510,0,2024-10-11
2024-10-14 17:17:13.824000-04:00,17:17:13.824000,62229230,228.71,231.730,228.60,231.30,39649642,578278,13,1,231.170,0,2,65,231.200,0,2024-10-14
2024-10-15 17:15:22.522000-04:00,17:15:22.522000,62115234,233.59,237.490,232.37,233.85,62233812,825377,1,7,23.369,0,3,1,23.374,0,2024-10-15
2024-10-16 17:16:28.200000-04:00,17:16:28.200000,62174487,231.52,232.120,229.84,231.78,33974915,548937,2,1,23.140,0,2,1,23.152,0,2024-10-16
2024-10-17 17:16:16.802000-04:00,17:16:16.802000,62175338,233.75,233.850,230.52,232.15,32756192,486062,2,65,232.030,0,1,1,232.120,0,2024-10-17
2024-10-18 17:15:06.179000-04:00,17:15:06.179000,62100358,236.00,236.180,234.01,235.00,46372722,560920,1,65,234.950,0,1,1,234.970,0,2024-10-18
2024-10-21 17:16:29.150000-04:00,17:16:29.150000,62186936,234.67,236.850,234.45,236.48,35293999,536391,1,7,236.550,0,4,1,236.570,0,2024-10-21
2024-10-22 17:16:28.878000-04:00,17:16:28.878000,62175174,233.84,236.220,232.60,235.86,38519533,487357,8,7,235.890,0,1,65,235.940,0,2024-10-22
2024-10-23 17:15:09.220000-04:00,17:15:09.220000,62103584,234.37,235.144,227.76,230.76,51987778,718515,2,1,230.350,0,1,1,230.450,0,2024-10-23
2024-10-24 17:15:52.932000-04:00,17:15:52.932000,62147462,230.00,230.820,228.41,230.57,29953675,488578,5,7,230.420,0,1,7,230.430,0,2024-10-24
2024-10-25 17:15:38.265000-04:00,17:15:38.265000,62136613,229.78,233.220,229.57,231.41,38679628,549855,1,7,231.230,0,3,1,231.320,0,2024-10-25

In [8]:
tsla = client.stocks_historical_eod_report(20241001, 20241030, 'tsla')
tsla

,ms_of_day,ms_of_day2,open,high,low,close,volume,count,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,,,,,
2024-10-01 17:15:31.446000-04:00,17:15:31.446000,62124023,262.66,263.9800,248.530,258.02,86971176,1150739,3,60,257.100,0,3,65,257.1600,0,2024-10-01
2024-10-02 17:15:59.927000-04:00,17:15:59.927000,62159081,247.78,251.1585,241.500,249.02,93700636,1247887,2,7,247.900,0,1,7,247.9900,0,2024-10-02
2024-10-03 17:16:09.545000-04:00,17:16:09.545000,62165076,244.50,249.7900,237.810,240.66,80274843,1036165,4,65,239.820,0,11,60,239.8800,0,2024-10-03
2024-10-04 17:17:19.925000-04:00,17:17:19.925000,62237960,246.62,250.9600,244.580,250.08,86486858,1099930,9,7,249.990,0,6,7,250.0000,0,2024-10-04
2024-10-07 17:15:01.254000-04:00,17:15:01.254000,62099977,248.97,249.8300,240.700,240.83,67732329,1011410,1,7,241.210,0,9,7,241.3000,0,2024-10-07
2024-10-08 17:17:18.325000-04:00,17:17:18.325000,62236353,243.66,246.2100,240.560,244.50,56083735,784793,2,7,244.060,0,1,1,244.1400,0,2024-10-08
2024-10-09 17:15:28.489000-04:00,17:15:28.489000,62128429,243.77,247.4300,239.510,241.05,65870996,898339,1,1,241.210,0,2,1,241.3100,0,2024-10-09
2024-10-10 17:15:33.941000-04:00,17:15:33.941000,62132880,241.81,242.7899,232.340,238.77,82428161,1079087,5,73,239.160,0,1,65,239.2800,0,2024-10-10
2024-10-11 17:16:25.092000-04:00,17:16:25.092000,62185046,219.86,223.3400,214.380,217.80,141939772,2085450,3,1,217.730,0,3,73,217.7700,0,2024-10-11
2024-10-14 17:17:13.824000-04:00,17:17:13.824000,62233579,220.16,221.9100,213.740,219.16,86022907,1337807,8,73,218.890,0,2,1,218.9300,0,2024-10-14
2024-10-15 17:15:22.522000-04:00,17:15:22.522000,62110701,220.00,224.2600,217.120,219.57,62758588,912262,2,65,21.907,0,3,65,21.9150,0,2024-10-15
2024-10-16 17:16:28.200000-04:00,17:16:28.200000,62173967,221.44,222.8199,218.930,221.33,49356094,728239,3,65,2.210,0,2,1,2.2105,0,2024-10-16
2024-10-17 17:16:16.802000-04:00,17:16:16.802000,62175406,221.34,222.0800,217.900,220.89,50666333,747799,4,65,220.980,0,5,65,221.0000,0,2024-10-17
2024-10-18 17:15:06.179000-04:00,17:15:06.179000,62097683,220.82,222.2800,219.230,220.70,49415379,684415,1,7,220.070,0,7,73,220.1000,0,2024-10-18
2024-10-21 17:16:29.150000-04:00,17:16:29.150000,62186908,219.00,220.4800,215.726,218.85,47144497,812363,2,73,218.610,0,5,7,218.6600,0,2024-10-21
2024-10-22 17:16:28.878000-04:00,17:16:28.878000,62186223,217.14,218.2200,215.260,217.97,43072612,722197,1,7,217.620,0,1,1,217.6800,0,2024-10-22
2024-10-23 17:15:09.220000-04:00,17:15:09.220000,62109148,217.00,218.7200,212.110,213.65,70363099,1082743,3,7,233.000,0,33,60,233.0500,0,2024-10-23
2024-10-24 17:15:52.932000-04:00,17:15:52.932000,62152802,244.80,262.1199,242.650,260.48,202544966,2559690,7,7,258.200,0,1,65,258.2500,0,2024-10-24
2024-10-25 17:15:38.265000-04:00,17:15:38.265000,62135402,255.80,269.4900,255.320,269.19,160715276,1894290,3,1,268.610,0,3,65,268.6500,0,2024-10-25