In [1]:
import os
import time

from thetadata import ThetaClient
from dotenv import load_dotenv

# Get environment variables in .env in project root
load_dotenv()

USERNAME=os.getenv('THETAUSER')
PASSWORD=os.getenv('THETAPASS')

client = ThetaClient(username=USERNAME, passwd=PASSWORD)
time.sleep(8) # TODO because it isn't started yet. Need to fix

If you require API support, feel free to join our discord server! http://discord.thetadata.us
[10-29-2024 12:35:49] INFO: Starting Theta Terminal v1.6.7 Revision A...
[10-29-2024 12:35:49] INFO: Config dir: C:\Users\david\ThetaData\ThetaTerminal
[10-29-2024 12:35:50] INFO: [MDDS] Attempting login as davidmckim@gmail.com
[10-29-2024 12:35:50] INFO: [FPSS] Attempting login as davidmckim@gmail.com
[10-29-2024 12:35:51] INFO: [MDDS] CONNECTED: [nj-a.thetadata.us:12000], Bundle: STOCK.FREE, OPTION.PRO, INDEX.FREE
[10-29-2024 12:35:51] INFO: [FPSS] CONNECTED: [nj-a.thetadata.us:20000], Bundle: STOCK.FREE, OPTION.PRO, INDEX.FREE

In [2]:
quotes = client.bulk_snapshots_bulk_quotes(
        exp=20241115,
        root="AAPL",
    )
quotes

,root,strike,right,ms_of_day,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,
2024-10-29 13:35:49.546000-04:00,AAPL,135.0,C,13:35:49.546000,85,60,99.10,50,38,60,99.60,50,2024-10-29
2024-10-29 13:35:59.166000-04:00,AAPL,220.0,P,13:35:59.166000,116,46,1.58,50,199,46,1.60,50,2024-10-29
2024-10-29 13:35:59.107000-04:00,AAPL,220.0,C,13:35:59.107000,400,5,15.95,50,38,11,16.05,50,2024-10-29
2024-10-29 13:35:57.758000-04:00,AAPL,135.0,P,13:35:57.758000,87,73,0.02,50,394,11,0.07,50,2024-10-29
2024-10-29 13:35:55.110000-04:00,AAPL,252.5,C,13:35:55.110000,428,46,0.68,50,329,46,0.70,50,2024-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-29 09:30:00.599000-04:00,AAPL,65.0,P,09:30:00.599000,0,46,0.00,50,20,46,0.01,50,2024-10-29
2024-10-29 13:35:58.129000-04:00,AAPL,150.0,C,13:35:58.129000,40,60,84.15,50,12,60,84.55,50,2024-10-29
2024-10-29 13:35:58.780000-04:00,AAPL,225.0,P,13:35:58.780000,200,46,2.60,50,2,46,2.63,50,2024-10-29
2024-10-29 13:35:55.081000-04:00,AAPL,150.0,P,13:35:55.081000,299,69,0.03,50,584,65,0.06,50,2024-10-29
2024-10-29 13:35:57.858000-04:00,AAPL,225.0,C,13:35:57.858000,300,5,12.00,50,236,11,12.10,50,2024-10-29

In [3]:
oi = client.bulk_snapshots_bulk_open_interest(
        exp=20241115,
        root="AAPL",
    )
oi

,root,strike,right,ms_of_day,open_interest,date
trade_datetime,,,,,,
2024-10-29 06:30:02-04:00,AAPL,135.0,C,06:30:02,748,2024-10-29
2024-10-29 06:30:06-04:00,AAPL,220.0,P,06:30:06,27730,2024-10-29
2024-10-29 06:30:14-04:00,AAPL,220.0,C,06:30:14,19203,2024-10-29
2024-10-29 06:30:22-04:00,AAPL,135.0,P,06:30:22,2728,2024-10-29
2024-10-29 06:30:20-04:00,AAPL,252.5,C,06:30:20,662,2024-10-29
...,...,...,...,...,...,...
2024-10-29 06:30:18-04:00,AAPL,65.0,P,06:30:18,739,2024-10-29
2024-10-29 06:30:02-04:00,AAPL,150.0,C,06:30:02,610,2024-10-29
2024-10-29 06:30:22-04:00,AAPL,225.0,P,06:30:22,22208,2024-10-29
2024-10-29 06:30:22-04:00,AAPL,150.0,P,06:30:22,5508,2024-10-29
2024-10-29 06:30:02-04:00,AAPL,225.0,C,06:30:02,27495,2024-10-29

In [4]:
ohlc = client.bulk_snapshots_bulk_ohlc(
        exp=20241115,
        root="AAPL",
    )
ohlc

,root,strike,right,ms_of_day,open,high,low,close,volume,count,date
trade_datetime,,,,,,,,,,,
2024-10-25 15:55:00.164000-04:00,AAPL,135.0,C,15:55:00.164000,96.55,96.55,96.55,96.55,1,1,2024-10-25
2024-10-29 13:34:50.101000-04:00,AAPL,220.0,P,13:34:50.101000,1.77,2.02,1.57,1.60,703,165,2024-10-29
2024-10-29 13:30:21.202000-04:00,AAPL,220.0,C,13:30:21.202000,15.70,16.10,15.29,15.90,24,13,2024-10-29
2024-10-28 09:39:50.756000-04:00,AAPL,135.0,P,09:39:50.756000,0.02,0.02,0.02,0.02,15,2,2024-10-28
2024-10-29 13:24:20.531000-04:00,AAPL,252.5,C,13:24:20.531000,0.60,0.70,0.60,0.70,11,10,2024-10-29
...,...,...,...,...,...,...,...,...,...,...,...
2024-10-25 15:48:39.884000-04:00,AAPL,65.0,P,15:48:39.884000,0.01,0.01,0.01,0.01,41,3,2024-10-25
2024-10-29 13:32:53.657000-04:00,AAPL,225.0,P,13:32:53.657000,3.00,3.25,2.58,2.68,1204,170,2024-10-29
2024-10-24 12:37:37.882000-04:00,AAPL,150.0,C,12:37:37.882000,80.00,80.00,80.00,80.00,1,1,2024-10-24
2024-10-29 13:19:10.583000-04:00,AAPL,225.0,C,13:19:10.583000,11.83,12.06,11.45,12.03,80,26,2024-10-29
2024-10-29 10:06:43.062000-04:00,AAPL,150.0,P,10:06:43.062000,0.03,0.04,0.03,0.04,6,2,2024-10-29

In [5]:
greeks = client.bulk_snapshots_bulk_greeks(
        exp=20241115,
        root="AAPL",
    )
greeks

,root,strike,right,ms_of_day,bid,ask,delta,theta,vega,rho,epsilon,lambda,implied_vol,iv_error,ms_of_day2,underlying_price,date
trade_datetime,,,,,,,,,,,,,,,,,
2024-10-29 13:36:02.003000-04:00,AAPL,135.0,C,13:36:02.003000,99.10,99.60,0.9927,-0.0401,1.0123,6.1963,-10.8235,2.3391,1.0976,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:36:02.527000-04:00,AAPL,220.0,P,13:36:02.527000,1.58,1.60,-0.1746,-0.1215,13.0073,-1.9785,1.9044,-25.7226,0.3239,-0.0002,48962556,234.08,2024-10-29
2024-10-29 13:36:02.063000-04:00,AAPL,220.0,C,13:36:02.063000,15.95,16.05,0.8190,-0.1401,13.2999,8.1842,-8.9295,11.9821,0.3332,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:57.758000-04:00,AAPL,135.0,P,13:35:57.758000,0.02,0.07,-0.0026,-0.0113,0.4092,-0.0304,0.0285,-15.4074,0.9500,-0.0041,48962556,234.08,2024-10-29
2024-10-29 13:36:02.549000-04:00,AAPL,252.5,C,13:36:02.549000,0.68,0.70,0.1069,-0.0759,9.3117,1.1343,-1.1665,36.3015,0.2724,0.0000,48962556,234.08,2024-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-29 09:30:00.599000-04:00,AAPL,65.0,P,09:30:00.599000,0.00,0.01,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.5000,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:59.830000-04:00,AAPL,225.0,P,13:35:59.830000,2.60,2.63,-0.2630,-0.1480,16.4843,-2.9893,2.8678,-23.5948,0.3127,-0.0001,48962556,234.08,2024-10-29
2024-10-29 13:35:58.129000-04:00,AAPL,150.0,C,13:35:58.129000,84.15,84.55,0.9919,-0.0373,1.1081,6.8864,-10.8150,2.7528,0.8937,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:55.081000-04:00,AAPL,150.0,P,13:35:55.081000,0.03,0.06,-0.0031,-0.0111,0.4860,-0.0364,0.0345,-18.6172,0.7812,-0.0028,48962556,234.08,2024-10-29
2024-10-29 13:36:01.889000-04:00,AAPL,225.0,C,13:36:01.889000,12.00,12.10,0.7318,-0.1663,16.6468,7.4172,-7.9785,14.2149,0.3216,0.0000,48962556,234.08,2024-10-29

In [6]:
greeks_second_order = client.bulk_snapshots_bulk_greeks_second_order(
        exp=20241115,
        root="AAPL",
    )
greeks_second_order

,root,strike,right,ms_of_day,bid,ask,gamma,vanna,charm,vomma,veta,implied_vol,iv_error,ms_of_day2,underlying_price,date
trade_datetime,,,,,,,,,,,,,,,,
2024-10-29 13:36:02.003000-04:00,AAPL,135.0,C,13:36:02.003000,99.10,99.60,0.0003,-0.0403,0.4734,4.9829,0.1410,1.0976,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:36:02.527000-04:00,AAPL,220.0,P,13:36:02.527000,1.58,1.60,0.0157,-0.6881,2.3183,32.5332,0.3829,0.3239,-0.0002,48962556,234.08,2024-10-29
2024-10-29 13:36:03.405000-04:00,AAPL,220.0,C,13:36:03.405000,15.95,16.05,0.0156,-0.6634,2.2988,30.5578,0.3866,0.3332,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:57.758000-04:00,AAPL,135.0,P,13:35:57.758000,0.02,0.07,0.0001,-0.0220,0.2241,3.1110,0.0730,0.9500,-0.0041,48962556,234.08,2024-10-29
2024-10-29 13:36:02.629000-04:00,AAPL,252.5,C,13:36:02.629000,0.68,0.70,0.0133,0.8804,-2.6392,55.2729,0.7545,0.2724,0.0000,48962556,234.08,2024-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-29 09:30:00.599000-04:00,AAPL,65.0,P,09:30:00.599000,0.00,0.01,0.0000,0.0000,0.0000,0.0000,0.0000,0.5000,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:59.830000-04:00,AAPL,225.0,P,13:35:59.830000,2.60,2.63,0.0206,-0.5910,1.8858,18.9302,0.3746,0.3127,-0.0001,48962556,234.08,2024-10-29
2024-10-29 13:35:58.129000-04:00,AAPL,150.0,C,13:35:58.129000,84.15,84.55,0.0004,-0.0543,0.5194,6.6170,0.1503,0.8937,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:55.081000-04:00,AAPL,150.0,P,13:35:55.081000,0.03,0.06,0.0002,-0.0315,0.2633,4.3483,0.0829,0.7812,-0.0028,48962556,234.08,2024-10-29
2024-10-29 13:36:01.889000-04:00,AAPL,225.0,C,13:36:01.889000,12.00,12.10,0.0202,-0.5623,1.8449,17.5650,0.3783,0.3216,0.0000,48962556,234.08,2024-10-29

In [7]:
greeks_third_order = client.bulk_snapshots_bulk_greeks_third_order(
        exp=20241115,
        root="AAPL",
    )
greeks_third_order

,root,strike,right,ms_of_day,bid,ask,speed,zomma,color,ultima,implied_vol,iv_error,ms_of_day2,underlying_price,date
trade_datetime,,,,,,,,,,,,,,,
2024-10-29 13:36:02.003000-04:00,AAPL,135.0,C,13:36:02.003000,99.10,99.60,0.0,0.0,-0.0194,10.8607,1.0976,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:36:02.527000-04:00,AAPL,220.0,P,13:36:02.527000,1.58,1.60,0.0,0.0,-0.0946,-100.0000,0.3239,-0.0002,48962556,234.08,2024-10-29
2024-10-29 13:36:03.917000-04:00,AAPL,220.0,C,13:36:03.917000,15.95,16.05,0.0,0.0,-0.0997,-100.0000,0.3332,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:36:03.635000-04:00,AAPL,135.0,P,13:36:03.635000,0.02,0.07,0.0,0.0,-0.0060,13.8041,0.9500,-0.0041,48962556,234.08,2024-10-29
2024-10-29 13:36:02.629000-04:00,AAPL,252.5,C,13:36:02.629000,0.68,0.70,0.0,0.0,-0.0547,-100.0000,0.2724,0.0000,48962556,234.08,2024-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-29 09:30:00.599000-04:00,AAPL,65.0,P,09:30:00.599000,0.00,0.01,0.0,0.0,0.0000,0.0000,0.5000,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:59.830000-04:00,AAPL,225.0,P,13:35:59.830000,2.60,2.63,0.0,0.0,-0.1182,-100.0000,0.3127,-0.0001,48962556,234.08,2024-10-29
2024-10-29 13:35:58.129000-04:00,AAPL,150.0,C,13:35:58.129000,84.15,84.55,0.0,0.0,-0.0173,17.2493,0.8937,0.0000,48962556,234.08,2024-10-29
2024-10-29 13:35:55.081000-04:00,AAPL,150.0,P,13:35:55.081000,0.03,0.06,0.0,0.0,-0.0059,22.1825,0.7812,-0.0028,48962556,234.08,2024-10-29
2024-10-29 13:36:03.929000-04:00,AAPL,225.0,C,13:36:03.929000,12.00,12.10,0.0,0.0,-0.1229,-100.0000,0.3216,0.0000,48962556,234.08,2024-10-29

In [8]:
client.kill()
client.status()

ERROR:root:TBD
ERROR:root:Could not get mdds status. Error: [WinError 10061] No connection could be made because the target machine actively refused it