In [1]:
import os
import time

from thetadata import ThetaClient
from dotenv import load_dotenv

# Get environment variables in .env in project root
load_dotenv()

USERNAME=os.getenv('THETAUSER')
PASSWORD=os.getenv('THETAPASS')

client = ThetaClient(username=USERNAME, passwd=PASSWORD)

In [3]:
eod = client.bulk_historical_data_bulk_eod(
    start_date=20241202,
    end_date=20241206,
    exp=20241206,
    root="AAPL",
)
eod

ERROR:root:Requesting URL('http://127.0.0.1:25510/v2/bulk_hist/option/eod?start_date=20241202&end_date=20241206&exp=20241206&root=AAPL&use_csv=true')

,root,strike,right,ms_of_day,ms_of_day2,open,high,low,close,volume,count,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,,,,,,,,
2024-12-02 17:23:37.542000-05:00,AAPL,100.0,C,17:23:37.542000,56598262,140.00,140.00,140.00,140.00,2,1,59,60,139.30,50,29,11,139.95,50,2024-12-02
2024-12-03 17:17:32.694000-05:00,AAPL,100.0,C,17:17:32.694000,0,0.00,0.00,0.00,0.00,0,0,59,60,142.35,50,56,60,143.00,50,2024-12-03
2024-12-04 17:19:39.652000-05:00,AAPL,100.0,C,17:19:39.652000,0,0.00,0.00,0.00,0.00,0,0,50,7,142.75,50,50,7,143.35,50,2024-12-04
2024-12-05 17:22:21.696000-05:00,AAPL,100.0,C,17:22:21.696000,0,0.00,0.00,0.00,0.00,0,0,50,7,142.65,50,50,7,143.40,50,2024-12-05
2024-12-06 17:22:31.813000-05:00,AAPL,100.0,C,17:22:31.813000,0,0.00,0.00,0.00,0.00,0,0,1,43,141.50,50,1,43,143.70,50,2024-12-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02 17:23:37.542000-05:00,AAPL,305.0,P,17:23:37.542000,0,0.00,0.00,0.00,0.00,0,0,55,7,65.10,50,55,7,65.75,50,2024-12-02
2024-12-03 17:17:32.694000-05:00,AAPL,305.0,P,17:17:32.694000,49454969,63.36,63.36,63.36,63.36,10,1,59,60,62.05,50,63,60,62.70,50,2024-12-03
2024-12-04 17:19:39.652000-05:00,AAPL,305.0,P,17:19:39.652000,36989541,61.65,61.65,61.65,61.65,10,1,55,7,61.70,50,58,7,63.15,50,2024-12-04
2024-12-05 17:22:21.696000-05:00,AAPL,305.0,P,17:22:21.696000,0,0.00,0.00,0.00,0.00,0,0,55,7,61.65,50,55,7,62.40,50,2024-12-05
2024-12-06 17:22:31.813000-05:00,AAPL,305.0,P,17:22:31.813000,0,0.00,0.00,0.00,0.00,0,0,29,11,60.35,50,29,11,64.30,50,2024-12-06

In [3]:
quote = client.bulk_historical_data_bulk_quote(
    start_date=20231023,
    end_date=20241024,
    exp=20241025,
    root="AAPL",
    ivl=3_600_000,
    start_time="12:30",
    end_time="14:59",
)
quote

,root,strike,right,ms_of_day,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,
2024-09-06 12:30:00-04:00,AAPL,100.0,C,12:30:00,39,47,121.15,50,64,7,121.80,50,2024-09-06
2024-09-06 13:30:00-04:00,AAPL,100.0,C,13:30:00,52,60,120.65,50,52,60,122.75,50,2024-09-06
2024-09-06 14:30:00-04:00,AAPL,100.0,C,14:30:00,63,7,119.65,50,62,7,122.30,50,2024-09-06
2024-09-09 12:30:00-04:00,AAPL,100.0,C,12:30:00,66,47,119.35,50,52,60,121.65,50,2024-09-09
2024-09-09 13:30:00-04:00,AAPL,100.0,C,13:30:00,52,60,120.20,50,52,60,122.00,50,2024-09-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-23 13:30:00-04:00,AAPL,300.0,P,13:30:00,61,60,69.65,50,61,60,70.25,50,2024-10-23
2024-10-23 14:30:00-04:00,AAPL,300.0,P,14:30:00,55,60,71.05,50,3,11,71.60,50,2024-10-23
2024-10-24 12:30:00-04:00,AAPL,300.0,P,12:30:00,30,11,70.20,50,69,60,71.10,50,2024-10-24
2024-10-24 13:30:00-04:00,AAPL,300.0,P,13:30:00,53,7,69.25,50,58,60,70.25,50,2024-10-24
2024-10-24 14:30:00-04:00,AAPL,300.0,P,14:30:00,57,60,69.30,50,59,60,70.05,50,2024-10-24

In [2]:
ohlc = client.bulk_historical_data_bulk_ohlc(
    start_date=20231023,
    end_date=20241024,
    exp=20241025,
    root="AAPL",
    ivl=3_600_000,
    start_time="12:30",
    end_time="14:59",
)
ohlc

,root,strike,right,ms_of_day,open,high,low,close,volume,count,date
trade_datetime,,,,,,,,,,,
2024-09-20 12:30:00-04:00,AAPL,100.0,C,12:30:00,0.0,0.0,0.0,0.0,0,0,2024-09-20
2024-09-20 13:30:00-04:00,AAPL,100.0,C,13:30:00,0.0,0.0,0.0,0.0,0,0,2024-09-20
2024-10-04 12:30:00-04:00,AAPL,100.0,C,12:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-04
2024-10-04 13:30:00-04:00,AAPL,100.0,C,13:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-04
2024-09-20 12:30:00-04:00,AAPL,100.0,P,12:30:00,0.0,0.0,0.0,0.0,0,0,2024-09-20
...,...,...,...,...,...,...,...,...,...,...,...
2024-09-30 13:30:00-04:00,AAPL,300.0,P,13:30:00,0.0,0.0,0.0,0.0,0,0,2024-09-30
2024-10-01 12:30:00-04:00,AAPL,300.0,P,12:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-01
2024-10-01 13:30:00-04:00,AAPL,300.0,P,13:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-01
2024-10-10 12:30:00-04:00,AAPL,300.0,P,12:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-10
2024-10-10 13:30:00-04:00,AAPL,300.0,P,13:30:00,0.0,0.0,0.0,0.0,0,0,2024-10-10

In [2]:
oi = client.bulk_historical_data_bulk_open_interest(
    start_date=20231023,
    end_date=20241024,
    exp=20241025,
    root="AAPL",
)
oi

,root,strike,right,ms_of_day,open_interest,date
trade_datetime,,,,,,
2024-09-09 06:30:16-04:00,AAPL,100.0,C,06:30:16,0,2024-09-09
2024-09-10 06:30:05-04:00,AAPL,100.0,C,06:30:05,0,2024-09-10
2024-09-11 06:30:14-04:00,AAPL,100.0,C,06:30:14,0,2024-09-11
2024-09-12 06:30:20-04:00,AAPL,100.0,C,06:30:20,0,2024-09-12
2024-09-13 06:30:15-04:00,AAPL,100.0,C,06:30:15,0,2024-09-13
...,...,...,...,...,...,...
2024-10-18 06:30:05-04:00,AAPL,300.0,P,06:30:05,0,2024-10-18
2024-10-21 06:30:01-04:00,AAPL,300.0,P,06:30:01,0,2024-10-21
2024-10-22 06:30:14-04:00,AAPL,300.0,P,06:30:14,0,2024-10-22
2024-10-23 06:30:24-04:00,AAPL,300.0,P,06:30:24,0,2024-10-23
2024-10-24 06:30:12-04:00,AAPL,300.0,P,06:30:12,0,2024-10-24

In [2]:
trade = client.bulk_historical_data_bulk_trade(
    start_date=20231023,
    end_date=20241024,
    exp=20241025,
    root="AAPL",
)
trade

,root,strike,right,ms_of_day,sequence,ext_condition1,ext_condition2,ext_condition3,ext_condition4,condition,size,exchange,price,condition_flags,price_flags,volume_type,records_back,date
trade_datetime,,,,,,,,,,,,,,,,,,
2024-09-20 15:55:52.104000-04:00,AAPL,100.0,C,15:55:52.104000,-780850882,255,255,255,255,131,1,5,130.57,0,7,0,0,2024-09-20
2024-10-04 15:53:51.123000-04:00,AAPL,100.0,C,15:53:51.123000,562270600,255,255,255,255,138,5,6,126.51,0,7,0,0,2024-10-04
2024-10-21 09:30:08.753000-04:00,AAPL,100.0,C,09:30:08.753000,514591913,255,255,255,255,18,2,1,135.01,0,7,0,0,2024-10-21
2024-10-21 09:30:08.754000-04:00,AAPL,100.0,C,09:30:08.754000,514592204,255,255,255,255,18,1,5,135.05,0,3,0,0,2024-10-21
2024-09-20 10:35:43.200000-04:00,AAPL,100.0,P,10:35:43.200000,-1902546980,255,255,255,255,18,1,7,0.01,0,7,0,0,2024-09-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-01 15:54:47.802000-04:00,AAPL,300.0,P,15:54:47.802000,661405502,255,255,255,255,130,1,65,73.95,0,3,0,0,2024-10-01
2024-10-01 15:54:47.870000-04:00,AAPL,300.0,P,15:54:47.870000,661410384,255,255,255,255,130,1,42,73.95,0,1,0,0,2024-10-01
2024-10-03 09:44:16.411000-04:00,AAPL,300.0,P,09:44:16.411000,2098823623,255,255,255,255,125,1,5,73.79,0,7,0,0,2024-10-03
2024-10-03 09:48:57.265000-04:00,AAPL,300.0,P,09:48:57.265000,2128558349,255,255,255,255,125,1,22,73.95,0,3,0,0,2024-10-03
2024-10-10 15:54:40.072000-04:00,AAPL,300.0,P,15:54:40.072000,1713468472,255,255,255,255,18,1,7,70.80,0,7,0,0,2024-10-10

In [2]:
trade_quote = client.bulk_historical_data_bulk_trade_quote(
    start_date=20231023,
    end_date=20241024,
    exp=20241025,
    root="AAPL",
)
trade_quote

,root,strike,right,ms_of_day,sequence,ext_condition1,ext_condition2,ext_condition3,ext_condition4,condition,...,ms_of_day2,bid_size,bid_exchange,bid,bid_condition,ask_size,ask_exchange,ask,ask_condition,date
trade_datetime,,,,,,,,,,,,,,,,,,,,,
2024-09-20 15:55:52.104000-04:00,AAPL,100.0,C,15:55:52.104000,-780850882,255,255,255,255,131,...,57349751,50,7,129.20,50,52,60,131.70,50,2024-09-20
2024-10-04 15:53:51.123000-04:00,AAPL,100.0,C,15:53:51.123000,562270600,255,255,255,255,138,...,57230074,30,76,126.30,50,52,60,126.80,50,2024-10-04
2024-10-21 09:30:08.753000-04:00,AAPL,100.0,C,09:30:08.753000,514591913,255,255,255,255,18,...,34208751,30,11,134.00,50,1,5,135.05,50,2024-10-21
2024-10-21 09:30:08.754000-04:00,AAPL,100.0,C,09:30:08.754000,514592204,255,255,255,255,18,...,34208753,30,11,134.00,50,1,5,135.05,50,2024-10-21
2024-09-20 10:35:43.200000-04:00,AAPL,100.0,P,10:35:43.200000,-1902546980,255,255,255,255,18,...,38136450,0,60,0.00,50,23,73,0.02,50,2024-09-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-01 15:54:47.802000-04:00,AAPL,300.0,P,15:54:47.802000,661405502,255,255,255,255,130,...,57285227,65,60,73.70,50,65,60,74.25,50,2024-10-01
2024-10-01 15:54:47.870000-04:00,AAPL,300.0,P,15:54:47.870000,661410384,255,255,255,255,130,...,57285227,65,60,73.70,50,65,60,74.25,50,2024-10-01
2024-10-03 09:44:16.411000-04:00,AAPL,300.0,P,09:44:16.411000,2098823623,255,255,255,255,125,...,35049956,62,60,72.85,50,62,60,74.50,50,2024-10-03
2024-10-03 09:48:57.265000-04:00,AAPL,300.0,P,09:48:57.265000,2128558349,255,255,255,255,125,...,35337261,92,60,73.40,50,87,60,75.05,50,2024-10-03
2024-10-10 15:54:40.072000-04:00,AAPL,300.0,P,15:54:40.072000,1713468472,255,255,255,255,18,...,57280057,10,60,70.30,50,59,60,70.80,50,2024-10-10

In [2]:
eod_greeks = client.bulk_historical_data_bulk_eod_greeks(
        start_date=20241024,
        end_date=20241024,
        exp=20241024,
        root="SPXW",
    )
eod_greeks

,root,strike,right,ms_of_day,open,high,low,close,volume,count,...,zomma,color,ultima,d1,d2,implied_vol,iv_error,ms_of_day2,underlying_price,date
trade_datetime,,,,,,,,,,,,,,,,,,,,,
2024-10-21 11:14:30.630000-04:00,SPXW,2400.0,C,11:14:30.630000,3435.25,3435.25,3435.25,3435.25,1,1,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0057,40470630,5853.98,2024-10-21
2024-10-22 00:00:00-04:00,SPXW,2400.0,C,00:00:00,0.00,0.00,0.00,0.00,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0,5851.20,2024-10-22
2024-10-23 10:06:02.664000-04:00,SPXW,2400.0,C,10:06:02.664000,3433.66,3433.66,3426.85,3426.85,2,2,...,0.0000,-0.2104,-0.0325,2.0075,1.5053,9.5945,0.0000,36362664,5797.42,2024-10-23
2024-10-24 03:16:03.511000-04:00,SPXW,2400.0,C,03:16:03.511000,3420.00,3420.00,3420.00,3420.00,3,1,...,0.0001,-0.0139,0.0432,2.3076,1.8860,20.7987,0.0000,11763511,5809.86,2024-10-24
2024-10-21 00:00:00-04:00,SPXW,2400.0,P,00:00:00,0.00,0.00,0.00,0.00,0,0,...,0.0000,0.0000,0.0000,19.7017,19.6564,0.5000,0.0000,0,5853.98,2024-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-24 14:39:52.558000-04:00,SPXW,7600.0,C,14:39:52.558000,0.05,0.05,0.05,0.05,38,23,...,0.0000,-0.0001,1.1212,-3.3338,-3.4134,3.9269,0.0145,52792558,5809.86,2024-10-24
2024-10-21 11:14:30.630000-04:00,SPXW,7600.0,P,11:14:30.630000,1762.55,1762.55,1762.55,1762.55,1,1,...,0.0000,-0.3988,-9.9769,-1.6073,-1.7620,1.7064,0.0000,40470630,5853.98,2024-10-21
2024-10-22 00:00:00-04:00,SPXW,7600.0,P,00:00:00,0.00,0.00,0.00,0.00,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0,5851.20,2024-10-22
2024-10-23 00:00:00-04:00,SPXW,7600.0,P,00:00:00,0.00,0.00,0.00,0.00,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0,5797.42,2024-10-23
2024-10-24 00:00:00-04:00,SPXW,7600.0,P,00:00:00,0.00,0.00,0.00,0.00,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0,5809.86,2024-10-24

In [2]:
all_greeks = client.bulk_historical_data_bulk_all_greeks(
        start_date=20241024,
        end_date=20241024,
        exp=20241024,
        root="SPXW",
        ivl=3_600_000,
    )
all_greeks

,root,strike,right,ms_of_day,bid,ask,delta,theta,vega,rho,...,ultima,d1,d2,dual_delta,dual_gamma,implied_vol,iv_error,ms_of_day2,underlying_price,date
trade_datetime,,,,,,,,,,,,,,,,,,,,,
2024-10-24 10:30:00-04:00,SPXW,2400.0,C,10:30:00,3402.7,3413.6,0.9982,-35.2145,0.6626,0.9816,...,0.0921,2.9191,2.5989,-0.9953,0.0,15.7982,0.0000,37800000,5807.07,2024-10-24
2024-10-24 11:30:00-04:00,SPXW,2400.0,C,11:30:00,3399.8,3405.2,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0006,41400000,5804.57,2024-10-24
2024-10-24 12:30:00-04:00,SPXW,2400.0,C,12:30:00,3397.6,3399.1,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,45000000,5798.39,2024-10-24
2024-10-24 13:30:00-04:00,SPXW,2400.0,C,13:30:00,3408.3,3409.8,0.9989,-20.8039,0.4125,0.9835,...,0.0877,3.0773,2.7753,-0.9972,0.0,14.8991,0.0000,48600000,5808.45,2024-10-24
2024-10-24 14:30:00-04:00,SPXW,2400.0,C,14:30:00,3406.4,3407.9,0.9993,-12.1833,0.2523,0.9846,...,0.0787,3.2330,2.9470,-0.9983,0.0,14.1053,0.0000,52200000,5806.81,2024-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-24 11:30:00-04:00,SPXW,7600.0,P,11:30:00,1794.8,1800.2,-0.9897,-58.9262,3.2093,-3.0996,...,1.5122,-2.3164,-2.4299,0.9924,0.0,5.6014,0.0000,41400000,5804.57,2024-10-24
2024-10-24 12:30:00-04:00,SPXW,7600.0,P,12:30:00,1800.9,1802.4,-0.9986,-6.5608,0.5180,-3.1201,...,1.5718,-3.0018,-3.0906,0.9989,0.0,4.3810,0.0000,45000000,5798.39,2024-10-24
2024-10-24 13:30:00-04:00,SPXW,7600.0,P,13:30:00,1790.2,1791.7,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0002,48600000,5808.45,2024-10-24
2024-10-24 14:30:00-04:00,SPXW,7600.0,P,14:30:00,1792.1,1793.6,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0001,52200000,5806.81,2024-10-24
2024-10-24 15:30:00-04:00,SPXW,7600.0,P,15:30:00,1782.3,1792.0,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0002,55800000,5812.29,2024-10-24

In [3]:
client.kill()
client.status()

ERROR:root:TBD
ERROR:root:Could not get mdds status. Error: [WinError 10061] No connection could be made because the target machine actively refused it